### PR TITLE
Add Airtable Resource Action

### PR DESCRIPTION
**Pull request by gjsyme**
Creates an action that will (for now, when triggered - commented out the scheduling) run a pull against the D_D Airtable readonly key to populate a RESOURCES.md page that resembles the current README.md.

Fails push at this time due to permissions on a push, and possibly the made up values I set.

Creating as draft PR to get visibility going; obvious change is the swap to scheduled and sorting out the push permission, maybe others to come in the comments.

### CODE REVIEW

**Comment by gjsyme** [comment]
@codingwithmanny kindly review as you know things about stuff. Open to anyone else, of course, particularly if you know things about stuff (github actions being the biggest interest).
The script will pull all records in the Resource Base airtable and put it in the markdown. We may want to update to just that which has been curated but I think the idea here is to put out all the things.
This worked on localhost against my own repo (hence the force push that blew out the updated file); was able to solve the problem with auth by using the GITHUB_TOKEN as a https github token for the URL. The scheduling is allegedly correct; I was running based upon the`act` CLI tool that just let me match on name.

**Comment by gjsyme** [comment]
I believe that this is ready to go now (rand against my own repo successfully before retargeting to this repo).

**Comment by codingwithmanny** [comment]
If it looks good to you @gjsyme then it LGTM.

**Comment by gjsyme** [comment]
I mean it's just blind faith that the github token will have proper permissions for itself.

**Comment by codingwithmanny** [comment]
Ah yes.. blind faith has gotten me through a lot of developer projects.

**Comment by gjsyme** [comment]
I think that RESOURCES.md is too pretty / curated to do well with automation. I've retargeted this to point at RESOURCES.md as has originally brought up by @codingwithmanny I think. Please either accept this or close it so I can clean up my main branch as it calls a failing workflow every night and emails me about it.

**Comment by ngnathan** [comment]
I'm good with that direction @gjsyme .  

Many thanks for pushing this through @gjsyme!!

**Pull request merged**
